# Generated by Django 4.1.1 on 2023-01-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(help_text='Введите описание товара', max_length=1000, verbose_name='Описание товара')),
                ('name', models.CharField(help_text='Введите имя продукта', max_length=30, verbose_name='Имя товара')),
                ('price', models.IntegerField(help_text='Введите цену товара', verbose_name='Цена товара')),
                ('cover', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите имя компании', max_length=30, verbose_name='Имя компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Введите тип продукта', max_length=100, verbose_name='Тип продукта')),
            ],
            options={
                'verbose_name': 'тип продукта',
                'verbose_name_plural': 'Типы продукции',
            },
        ),
        migrations.CreateModel(
            name='Sum_of_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_of_article', models.IntegerField(help_text='Введите число товара', verbose_name='Количество товара')),
                ('article', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='manuals.article', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Количество',
                'verbose_name_plural': 'Количество',
            },
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_back', models.DateField(help_text='Дата окончания статуса', verbose_name='Дата окончания статуса')),
                ('article', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='manuals.article', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='company',
            field=models.ForeignKey(help_text='Введите компанию товара', on_delete=django.db.models.deletion.CASCADE, to='manuals.companys', verbose_name='Компания товара'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(help_text='Введите тип товара', on_delete=django.db.models.deletion.DO_NOTHING, to='manuals.type', verbose_name='Тип/типы товаров'),
        ),
    ]
